FROM alpine:3.22
RUN addgroup -g 10001 bench \
    && adduser -D -u 10001 -G bench -h /home/bench bench
COPY --chmod=0755 fake-codex.sh /usr/local/bin/codex
COPY --chmod=0755 fake-entrypoint.sh /usr/local/bin/bench-entrypoint
COPY --chmod=0755 fake-image-info.sh /usr/local/bin/bench-image-info
ENV BENCH_AGENT=codex
ENTRYPOINT ["/usr/local/bin/bench-entrypoint"]
